pyms:
  requests:
    data: ""
  swagger:
    path: "swagger"
    file: "swagger.yaml"
    url: "/ui/"
  tracer:
    client: "jaeger"
    host: "localhost"
    component_name: "Python Microservice"
ms:
  DEBUG: false
  TESTING: false
  APP_NAME: {{ cookiecutter.project_slug }}
  APPLICATION_ROOT : {{ cookiecutter.application_root }}
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SECRET_KEY: "gjr39dkjn344_!67#"
  DATABASE: db.sqlite3
  SQLALCHEMY_DATABASE_URI: sqlite:////microservice/database/db.sqlite3